// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/path-config": {
    params: {};
  };
  "/api-config": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/path-config" | "/api-config" | "/*";
  };
  "routes/[path-config]._index.jsx": {
    id: "routes/[path-config]._index";
    page: "/path-config";
  };
  "routes/[api-config]._index.jsx": {
    id: "routes/[api-config]._index";
    page: "/api-config";
  };
  "routes/_index.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/[404]._index.jsx": {
    id: "routes/[404]._index";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/[path-config]._index": typeof import("./app/routes/[path-config]._index.jsx");
  "routes/[api-config]._index": typeof import("./app/routes/[api-config]._index.jsx");
  "routes/_index": typeof import("./app/routes/_index.jsx");
  "routes/[404]._index": typeof import("./app/routes/[404]._index.jsx");
};